LNX-183 Add take action with inventory
group-project-gut/lynx-python-common pull request #26
Opened 2023-08-27 14:26 UTC by EasyJB

2023-09-01 16:35 UTC, Krystian030 approved these changes

2023-09-04 20:14 UTC, filip-szweda requested changes

2023-09-04 20:14 UTC, filip-szweda commented on lynx/common/actions/common_requirements.py
> +            if all(element in object.tags for element in given_tags):
`element` -> `tag`/`given_tag`

2023-09-04 20:14 UTC, filip-szweda commented on lynx/common/actions/common_requirements.py
> +    def any_object_has_given_tags_on_squere(scene: Scene, position: Vector, given_tags: List[str]) -> bool:
`any_object_on_square_has_all_given_tags`

2023-09-04 20:14 UTC, filip-szweda commented on lynx/common/actions/take.py
> +    Simple action used to hit/destroy object, which stands on the given destination.
Please, provide more adequate description

2023-09-04 20:14 UTC, filip-szweda commented on tests/common_requirements_test.py
> +class TestIsAnyTagOnSquare:
Adpt to new function name

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +
No need for this line, same goes below

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +        expected_scene.add_entity(expected_dummy_take)
No need for adding `Action` entities when not comparing the whole `Scene`
Same in other test classes

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +    def test_apply__positive(self):
`test_take_only_wood_from_square_with_multiple_objects_positive`

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +    def test_apply_positive(self):
`test_take_single_wood_from_square_positive`

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +    def test_requirements_too_far_fail(self):
`test_object_too_far_negative`

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +    def test_requirements_no_pickable_fail(self):
`test_object_without_pickable_tag_negative`

2023-09-04 20:14 UTC, filip-szweda commented on tests/take_test.py
> +    def test_requirements_positive(self):
`test_all_requirements_satisifed_positive`

2023-09-07 18:42 UTC, filip-szweda approved these changes

2023-09-07 18:42 UTC, merged